pragma Singleton
import QtQuick

// Every user-visible string, in Turkish and English. ScribeHost sets `lang` from the `ui` setting
// ("auto" follows $LANG), and everything reads `Strings.s.<key>`, so a change applies live.
QtObject {
    id: strings

    property string lang: "en"          // "tr" | "en"
    readonly property var s: lang === "tr" ? tr : en

    readonly property var tr: ({
        // overlay
        dragRegion: "Alanı sürükle      Esc iptal",
        reading: "OKUNUYOR",
        dragHint: "Metni sürükleyerek seç",
        lowConf: function (n) { return "Güven düşük (%" + n + ")  ·  yine de seçebilirsin"; },
        noText: "Metin bulunamadı",
        noLang: "Dil paketi eksik",
        copy: "Kopyala",
        copied: "Kopyalandı",
        selectAll: "Tümünü seç",
        // settings
        settings: "Ayarlar",
        readingLangs: "OKUMA DİLLERİ",
        installed: "kurulu",
        download: "İndir",
        howInstall: function (name) { return name + " nasıl kurulsun?"; },
        direct: "Doğrudan indir",
        directHint: "Parola gerekmez, ev klasörüne iner",
        viaPm: "Paket yöneticisiyle kur",
        asksPassword: "parola ister",
        copyCommand: "Komutu kopyala",
        runTerminal: "Terminalde çalıştır",
        terminalOpen: "Terminal açık, bitince liste yenilenir",
        installInfo: function (pm, os) {
            return "İndir'e basınca iki yol sunulur: parolasız doğrudan indirme ya da " + pm
                + (os ? " (" + os + ")" : "") + " ile kurulum (parola ister).";
        },
        pmFallback: "paket yöneticisi",
        behaviour: "DAVRANIŞ",
        closeAfterCopy: "Kopyalayınca kapat",
        autoCopy: "Okuyunca hepsini kopyala",
        joinLines: "Paragraf satırlarını birleştir",
        highlight: "VURGU RENGİ",
        scanAnim: "TARAMA ANİMASYONU",
        scanNames: { line: "Çizgi", rows: "Satır satır", shine: "Parıltı", pixels: "Piksel", ring: "Çevre", focus: "Odak" },
        interfaceLang: "ARAYÜZ DİLİ",
        auto: "Otomatik",
        // host
        missing: function (list) { return "Eksik: " + list; },
        grabFailed: "Ekran görüntüsü alınamadı (grim).",
        readFailed: function (why) { return "Okuma başarısız oldu (" + why + ")."; },
        readTimeout: "Okuma çok uzun sürdü, iptal edildi.",
        terminalClosed: "Terminal kapandı, dil listesi yenilendi.",
        installFailed: "Kurulum başarısız oldu.",
        commandCopied: "Komut kopyalandı, terminale yapıştır.",
        // translation
        translate: "Çevir",
        translating: "çevriliyor…",
        original: "ORİJİNAL",
        originalEditable: "ORİJİNAL · düzenlenebilir",
        detected: "algılandı",
        local: "yerel",
        online: "çevrimiçi",
        sec: "sn",
        copyTranslation: "Çeviriyi kopyala",
        copyOriginal: "Orijinali kopyala",
        originalBtn: "Orijinal",
        edit: "Düzenle",
        dictHint: "kelimenin üstüne gel: sözlük",
        dictSearching: "aranıyor…",
        dictSame: "karşılık bulunamadı, aynen kalıyor",
        dictBlocked: "Çevrimiçi izin gerekli. Çeviri kartından onayla.",
        dictNoModel: "Çeviri paketi kurulu değil.",
        noModelTitle: function (pair) { return pair + " paketi kurulu değil"; },
        noModelBody: "Bir kez indirilir (yaklaşık 350 MB), sonra internet gerekmez.",
        unsupportedTitle: "Bu dil çifti çevrimdışı desteklenmiyor",
        unsupportedBody: "Çevrimdışı yalnızca İngilizce ↔ Türkçe var. Diğer diller için çevrimiçi çeviri gerekir.",
        install: "İndir",
        useOnline: "Çevrimiçi kullan",
        close: "Kapat",
        installingTitle: "Çeviri paketi kuruluyor",
        cancel: "İptal",
        consentTitle: "Metin MyMemory'ye gönderilecek",
        consentBody: "Seçtiğin alandaki yazı internete çıkar. Şifre ve özel mesajlarda çevrimdışı çeviriyi kullan.",
        sendOnce: "Bir kez gönder",
        allowAlways: "Her zaman izin ver",
        giveUp: "Vazgeç",
        trFailed: "Çeviri başarısız oldu.",
        trNetwork: "Çevrimiçi çeviri başarısız (bağlantı ya da günlük kota).",
        trService: "Çeviri servisi yanıt vermedi.",
        // translation settings
        enableTranslate: "Çeviriyi etkinleştir",
        enableWarnTitle: "ETKİNLEŞTİRMEDEN ÖNCE",
        enableNet: "İnternet: çevrimdışı çeviriyi kurmak için bir kez yaklaşık 350 MB indirilir (PyPI paketleri ve Argos Translate modelleri). Çevrimiçi motoru seçersen okunan metin MyMemory servisine gönderilir.",
        enableMem: "Bellek: Çevir'e bastığında model yüklenir (260–440 MB), 2 dakika boşta kalınca bırakılır.",
        enableDisk: "Disk: yaklaşık 470 MB, ~/.local/share/scribe-translate altında. Aşağıdaki Kaldır ile silinir.",
        enableOff: "Kapalıyken hiçbir şey indirilmez, yüklenmez ya da çalıştırılmaz.",
        enableAcc: "Doğruluk: çevrimdışı çeviri küçük bir modeldir ve hata yapabilir. Önemli metinlerde sonucu kontrol et.",
        offlineCaveat: "Çevrimdışı çeviri hata yapabilir. Küçük bir modeldir: bağlamı yanlış anlayabilir, bir kelimeyi özne sanabilir ya da çevirmeden bırakabilir. Örneğin \"Avlu bahçesi … kapalı olacaktır\" cümlesinde \"Avlu\"yu özne sanıp \"Avlu garden will be closed\" diyebildi. Önemli metinlerde sonucu kontrol et.",
        enableConfirm: "Etkinleştir",
        translation: "ÇEVİRİ",
        autoTranslate: "Okuyunca hemen çevir",
        resultView: "SONUÇ GÖRÜNÜMÜ",
        viewCard: "Kart",
        viewInplace: "Yerinde",
        engine: "ÇEVİRİ MOTORU",
        engineOffline: "Çevrimdışı",
        engineOnline: "Çevrimiçi",
        targetLang: "HEDEF DİL",
        allowOnline: "Çevrimiçi çeviriye izin ver",
        onlineEmail: "MyMemory e-postası (isteğe bağlı)",
        onlineEmailHint: "Günlük kotayı 5.000'den 50.000 karaktere çıkarır",
        features: "ÖZELLİKLER",
        smartActions: "Akıllı eylemler (link, e-posta, telefon, IBAN)",
        dictionary: "Kelime sözlüğü (çeviri açıkken, üstüne gelince)",
        editable: "Okunan metin düzenlenebilsin",
        offlineTitle: "ÇEVRİMDIŞI ÇEVİRİ",
        offlineInfo: "Metin bilgisayarından çıkmaz, internet gerekmez. Şu an yalnızca İngilizce ↔ Türkçe. Bir kez indirilir (yaklaşık 350 MB); yalnızca Çevir'e basınca belleğe yüklenir, 2 dakika boşta kalınca kapanır.",
        offlineChecking: "Denetleniyor…",
        offlineReady: "Kurulu",
        offlinePartial: "Eksik kurulu",
        offlineMissing: "Kurulu değil",
        installOffline: "İndir ve kur",
        reinstallOffline: "Yeniden kur",
        removeOffline: "Kaldır",
        removeOfflineHint: "Ortamı ve modelleri siler",
        diskUse: function (mb) { return mb + " MB disk"; },
        memWarnTitle: "BELLEK UYARISI",
        memWarn: "Çevrimdışı çeviri modeli yüklüyken yaklaşık 260 MB, çeviri yaptıkça 440 MB'a kadar bellek kullanır. Model yalnızca Çevir'e bastığında yüklenir ve son kullanımdan 2 dakika sonra bellekten kalkar. Çevir'e basmadıkça bellek kullanılmaz. Belleği az olan bilgisayarlarda çevrimiçi motoru seçebilirsin.",
        memNow: function (mb) { return "şu an " + mb + " MB kullanıyor"; },
        serviceUp: "servis çalışıyor",
        serviceIdle: "servis beklemede",
        tlNames: ({
            tr: "Türkçe", en: "İngilizce", de: "Almanca", fr: "Fransızca", es: "İspanyolca", it: "İtalyanca",
            pt: "Portekizce", ru: "Rusça", nl: "Felemenkçe", pl: "Lehçe", ar: "Arapça", ja: "Japonca",
            ko: "Korece", zh: "Çince", auto: "Otomatik"
        }),
        langNames: ({
            tur: "Türkçe", eng: "İngilizce", deu: "Almanca", fra: "Fransızca", spa: "İspanyolca",
            ita: "İtalyanca", por: "Portekizce", nld: "Felemenkçe", pol: "Lehçe", ukr: "Ukraynaca",
            rus: "Rusça", ara: "Arapça", jpn: "Japonca", kor: "Korece", chi_sim: "Çince (Basit)"
        })
    })

    readonly property var en: ({
        dragRegion: "Drag a region      Esc to cancel",
        reading: "READING",
        dragHint: "Drag over the text to select it",
        lowConf: function (n) { return "Low confidence (" + n + "%)  ·  you can still select"; },
        noText: "No text found",
        noLang: "Language pack missing",
        copy: "Copy",
        copied: "Copied",
        selectAll: "Select all",
        settings: "Settings",
        readingLangs: "READING LANGUAGES",
        installed: "installed",
        download: "Download",
        howInstall: function (name) { return "How should " + name + " be installed?"; },
        direct: "Download directly",
        directHint: "No password, saved in your home folder",
        viaPm: "Install with the package manager",
        asksPassword: "asks for a password",
        copyCommand: "Copy command",
        runTerminal: "Run in terminal",
        terminalOpen: "Terminal is open, the list refreshes when it closes",
        installInfo: function (pm, os) {
            return "Download offers two ways: a direct download without a password, or " + pm
                + (os ? " (" + os + ")" : "") + " which asks for one.";
        },
        pmFallback: "your package manager",
        behaviour: "BEHAVIOUR",
        closeAfterCopy: "Close after copy",
        autoCopy: "Copy everything after reading",
        joinLines: "Join the lines of a paragraph",
        highlight: "HIGHLIGHT COLOUR",
        scanAnim: "SCAN ANIMATION",
        scanNames: { line: "Line", rows: "Row by row", shine: "Shine", pixels: "Pixels", ring: "Outline", focus: "Focus" },
        interfaceLang: "INTERFACE LANGUAGE",
        auto: "Auto",
        missing: function (list) { return "Missing: " + list; },
        grabFailed: "Could not take the screenshot (grim).",
        readFailed: function (why) { return "Reading failed (" + why + ")."; },
        readTimeout: "Reading took too long and was cancelled.",
        terminalClosed: "Terminal closed, the language list was refreshed.",
        installFailed: "Installation failed.",
        commandCopied: "Command copied, paste it into a terminal.",
        // translation
        translate: "Translate",
        translating: "translating…",
        original: "ORIGINAL",
        originalEditable: "ORIGINAL · editable",
        detected: "detected",
        local: "local",
        online: "online",
        sec: "s",
        copyTranslation: "Copy translation",
        copyOriginal: "Copy original",
        originalBtn: "Original",
        edit: "Edit",
        dictHint: "hover a word: dictionary",
        dictSearching: "looking up…",
        dictSame: "no equivalent found, kept as is",
        dictBlocked: "Online permission needed. Allow it on the translation card.",
        dictNoModel: "Translation pack not installed.",
        noModelTitle: function (pair) { return pair + " pack is not installed"; },
        noModelBody: "Downloaded once (about 350 MB), then no internet is needed.",
        unsupportedTitle: "This language pair is not available offline",
        unsupportedBody: "Offline only covers English ↔ Turkish. Other languages need online translation.",
        install: "Download",
        useOnline: "Use online",
        close: "Close",
        installingTitle: "Installing the translation pack",
        cancel: "Cancel",
        consentTitle: "The text will be sent to MyMemory",
        consentBody: "What is in the selected region leaves your computer. For passwords and private messages use offline translation.",
        sendOnce: "Send once",
        allowAlways: "Always allow",
        giveUp: "Cancel",
        trFailed: "Translation failed.",
        trNetwork: "Online translation failed (connection or daily quota).",
        trService: "The translation service did not answer.",
        enableTranslate: "Enable translation",
        enableWarnTitle: "BEFORE YOU ENABLE IT",
        enableNet: "Internet: installing offline translation downloads about 350 MB once (PyPI packages and Argos Translate models). If you pick the online engine, the text that was read is sent to the MyMemory service.",
        enableMem: "Memory: the model is loaded when you press Translate (260–440 MB) and released after 2 idle minutes.",
        enableDisk: "Disk: about 470 MB under ~/.local/share/scribe-translate. Remove deletes it.",
        enableOff: "While it is off nothing is downloaded, loaded or run.",
        enableAcc: "Accuracy: offline translation is a small model and can be wrong. Check the result when it matters.",
        offlineCaveat: "Offline translation can be wrong. It is a small model: it may misread the context, take a word for the subject or leave it untranslated. For example it turned \"Avlu bahçesi … kapalı olacaktır\" into \"Avlu garden will be closed\". Check the result when it matters.",
        enableConfirm: "Enable",
        translation: "TRANSLATION",
        autoTranslate: "Translate right after reading",
        resultView: "RESULT VIEW",
        viewCard: "Card",
        viewInplace: "In place",
        engine: "TRANSLATION ENGINE",
        engineOffline: "Offline",
        engineOnline: "Online",
        targetLang: "TARGET LANGUAGE",
        allowOnline: "Allow online translation",
        onlineEmail: "MyMemory e-mail (optional)",
        onlineEmailHint: "Raises the daily quota from 5,000 to 50,000 characters",
        features: "FEATURES",
        smartActions: "Smart actions (links, e-mail, phone, IBAN)",
        dictionary: "Word dictionary (while a translation is open, on hover)",
        editable: "Let the read text be edited",
        offlineTitle: "OFFLINE TRANSLATION",
        offlineInfo: "The text never leaves your computer and no internet is needed. English ↔ Turkish only for now. Downloaded once (about 350 MB); loaded into memory only when you press Translate and unloaded after 2 idle minutes.",
        offlineChecking: "Checking…",
        offlineReady: "Installed",
        offlinePartial: "Partly installed",
        offlineMissing: "Not installed",
        installOffline: "Download and install",
        reinstallOffline: "Reinstall",
        removeOffline: "Remove",
        removeOfflineHint: "Deletes the environment and the models",
        diskUse: function (mb) { return mb + " MB on disk"; },
        memWarnTitle: "MEMORY WARNING",
        memWarn: "While loaded, the offline translation model uses about 260 MB of memory, up to 440 MB as you translate. It is only loaded when you press Translate and unloaded 2 minutes after the last use. Nothing is used until you press it. On computers with little memory you can pick the online engine instead.",
        memNow: function (mb) { return "using " + mb + " MB right now"; },
        serviceUp: "service running",
        serviceIdle: "service idle",
        tlNames: ({
            tr: "Turkish", en: "English", de: "German", fr: "French", es: "Spanish", it: "Italian",
            pt: "Portuguese", ru: "Russian", nl: "Dutch", pl: "Polish", ar: "Arabic", ja: "Japanese",
            ko: "Korean", zh: "Chinese", auto: "Auto"
        }),
        langNames: ({
            tur: "Turkish", eng: "English", deu: "German", fra: "French", spa: "Spanish",
            ita: "Italian", por: "Portuguese", nld: "Dutch", pol: "Polish", ukr: "Ukrainian",
            rus: "Russian", ara: "Arabic", jpn: "Japanese", kor: "Korean", chi_sim: "Chinese (Simplified)"
        })
    })
}
